FROM jupyter/minimal-notebook

USER root

RUN apt-get update && apt-get install -y \
        libopenblas-dev \
        g++ \
        git \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install git+git://github.com/Theano/Theano.git@0.8.X
EXPOSE 8888

USER jovyan

COPY notebook notebook
RUN mkdir data && cd data && wget http://www.iro.umontreal.ca/~lisa/deep/data/mnist/mnist_py3k.pkl.gz -O mnist.pkl.gz

CMD ["/start-notebook.sh"]